name: Feature Request
description: Suggest a new feature for Matroska Batch Flow
labels: [enhancement]
body:
  - type: markdown
    id: introduction
    attributes:
      value: |
        ### Thank you for suggesting a feature!
        Please keep in mind that Matroska Batch Flow is a free and open-source project maintained by volunteers in their spare time. Please provide as much detail as possible to help us understand your idea and its potential impact.
  - type: checkboxes
    id: before-posting
    attributes:
      label: "Before submitting this feature request:"
      options:
        - label: This is a **feature request**, not a bug or question.
          required: true
        - label: I have searched existing issues to make sure this feature has not already been requested.
          required: true
        - label: This request addresses only a single feature or improvement.
          required: true
  - type: textarea
    id: feature-description
    attributes:
      label: Description of the feature
      description: Please provide a clear and detailed description of the feature or improvement.
      placeholder: |
        Describe the feature, its purpose, and how it would improve Matroska Batch Flow.
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: What problem does this feature solve?
      placeholder: |
        Explain the scenario or user story that motivates this feature.
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
      description: How do you imagine this feature working? Any specific ideas for implementation?
      placeholder: |
        Describe your vision for how the feature should work.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        List any alternatives you've thought about.
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or mockups
      description: Attach relevant screenshots or mockups related to this feature request.
  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: Any other information that might be useful for evaluating the feature.